- include: ../../vxflexos-common/tasks/install_vxflexos.yaml

- name: "display inventory"
  debug:
    msg: "{{ item }}"
  loop: "{{ groups['sdss'] }}"

- name: Display SDS name
  debug:
   var: hostvars[inventory_hostname]['ansible_hostname']

- name: Display SDS IP
  debug:
    var: hostvars[inventory_hostname]['ansible_'+cluster_interface]['ipv4']['address']

- name: show current host information
  debug:
    msg: "host is {{ inventory_hostname }}"

- name: allow traffic on 7072
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 7072
    jump: ACCEPT
    action: insert

- name: login to MDM
  command: scli --login --username admin --password "{{ password }}" --approve_certificate
  run_once: true
  delegate_to: "{{ vxflexos_mdm_mgmt_ip }}"

- name: add SDS
  command: >
    scli --add_sds 
    --sds_ip {{ hostvars[inventory_hostname]['ansible_'+cluster_interface]['ipv4']['address'] }} 
    --storage_pool_name {{ storage_pool }} 
    --sds_name "{{ hostvars[inventory_hostname]['ansible_hostname'] }}" 
    --protection_domain_name {{ protection_domain }} 
    --device_path {{ sds_disks|join(',') }}
    --force_device_takeover
    --i_am_sure
  retries: 10
  delay: 5
  register: add_devices
  until: add_devices.rc == 0
  delegate_to: "{{ vxflexos_mdm_mgmt_ip }}"
  when: sds_disks > 0

