---
- name: Upload package wrapper
  template: dest="/var/tmp/package_wrapper.sh" src="roles/vxflexos-common/templates/package_wrapper.sh.j2" mode="0775" owner="root" group="root" force="yes"

- include: "install_vxflexos_redhat.yaml"
